# Generated by Django 5.0.4 on 2024-04-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='formal_name',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
